name: webitel_desk_track
description: "Webitel Desk Track Application"

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  tray_manager: ^0.5.0
  flutter_phoenix: ^1.1.1
  desktop_screenshot:
    git:
      url: https://github.com/vhunkalo/desktop_screenshot.git
  flutter_dotenv: ^5.2.1
  flutter_inappwebview: ^6.1.5
  http: ^1.4.0
  web_socket_channel: ^3.0.3
  path_provider: ^2.1.5
  screen_capturer: ^0.2.3
  logger: ^2.6.0
  connectivity_plus: ^6.1.4
  retry: ^3.1.2
  flutter_webrtc: ^0.14.2
  flutter_svg: ^2.2.0
  uuid: ^4.5.1
  file_selector: ^1.0.3
  shared_preferences: ^2.5.3
  ffmpeg_kit_flutter_new: ^3.2.0
  flutter_secure_storage: ^9.2.4
  flutter_secure_storage_windows: ^3.1.2
  mime: ^2.0.0
  http_parser: ^4.1.2
  win32: ^5.15.0
  msix: ^3.16.12
  window_manager:
    git:
      url: https://github.com/vhunkalo/window_manager.git
      ref: main
      path: packages/window_manager



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4



flutter_gen:
  output: lib/gen/
  assets:
    enabled: true
    outputs:
      class_name: Assets
  fonts:
    enabled: true


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - .env

  fonts:
    - family: montserrat
      fonts:
        - asset: assets/fonts/montserrat/static/montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/static/montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/static/montserrat-Italic.ttf
          style: italic
